# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'keyChainExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'KeychainSwift'
  # Pods for keyChainExample

  target 'keyChainExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'keyChainExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
